services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - DEBUG=${DEBUG:-0}
    networks:
      - sam-local-net
  db:
    image: postgres:18
    container_name: ticketmaster-postgres
    environment:
      POSTGRES_USER: ticketmaster
      POSTGRES_PASSWORD: ticketmaster
      POSTGRES_DB: ticketmasterdb
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:

networks:
    sam-local-net:
      name: sam-local-net
      driver: bridge